### ISSUE TITLE
Create proposal for ways to improve use of Google Analytics

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#188]
How can we use Google Analytics to better measure our OKRs and performance? Create a proposal with some ideas.

**Comment by bonnieAcameron** [comment]
3 Underutilized areas of Google Analytics:

**Tag Manager**

Google Tag manager is a free extension that works with Google Analytics. Without adding code, you can tell GTM what to measure and send to Google Analytics for further analysis. A few things that we could be measuring are: 

Downloads (pdfs, etc)
Scrolls (how far down a page people scroll)
Clicks (are people clicking on necessary links?)
Forms
Videos

Having this capability could allow us to more easily answer the questions:

- What are our users coming to our site to do?
- Are users reading our guidance?

**Campaigns**

Since Go.USA.gov is being deprecated, we need a replacement tool to be able to track link performance. Google Analytics has a native capability to track campaign snippets and their performance, and automatically analyze and export them. Campaigns can also work with Tag Manager to track the performance of outreach efforts.

**Behavior Flow**

We can use this out-of-the-box Google Analytics tool to get an overview of how people move through the site. By pinpointing average user behavior as they move through pages like "Components," we can better understand if people are easily finding what they need (for example, are they going in circles? bouncing from pages? etc.) This is a qualitative way of indicating whether a page is meeting its intended purpose.
