### ISSUE TITLE
Kickoff: Getting started_custom user guides

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#88]
Tasks: 
- [x] Conduct initial discovery/ kick off sessions
- [x] Create persona board with sections for role-specific questions.
- [x] Identify existing relevant resources, capture questions and top tasks for each persona based on those resources (past research)
- [x] Thee role-based workshops are conducted the week of Aug 16. 

DoD
- [x] Follow up tasks and  [issues created ](https://github.com/uswds/uswds/issues/4302)

**Comment by sofya-UX** [comment]
@jAigret-Bix here is my update:

- I created persona board with sections for role-specific questions in [this Mural​​​​​​​](https://app.mural.co/t/gsa6/m/gsa6/1626894706921/a864546183d28ddd3a1dcbb5ff2fe641f81376b7?sender=uf90a6e8e2ff5dc4049236267)
- I identified existing relevant resources (and documented them in the above Mural as well)
- I reviewed our November 2020 personas and pulled in questions and top tasks into mural boards 
- I reviewed about half of [Accelerator interviews and Blueprint Synthesis Mural](https://app.mural.co/t/gsa6/m/flexion6734/1604606004114/7e942190d1a8bf96cb6aa25011206b9a13fb6b9c?sender=uf90a6e8e2ff5dc4049236267) and capture questions and top tasks for each persona based on those resources. I briefed @katieekline on where exactly I stopped, so that se can pick it up from there, if needed.

**Comment by jAigret-Bix** [comment]
@thisisdano  Kick off for custom tailored guides are complete and [follow up issue created](https://github.com/uswds/uswds/issues/4302). Issue is ready for acceptance and to be closed

**Comment by thisisdano** [comment]
Done!
